service: pave-the-way-bff

provider:
  name: google
  stage: dev
  runtime: nodejs8
  region: us-central1
  project: my-project
  credentials: ~/.gcloud/keyfile.json

plugins:
  - serverless-google-cloudfunctions


package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  search:
    handler: http
    dis:
      - http: functions/search.search
